/**
 * 프로젝트 전체 로그 액션명 정리
 * isAuditLog, isErrorLog 함수에서 추출하여 카테고리별로 정리
 */

// ============================================
// 인증 관련 액션 (auth)
// ============================================
export const AUTH_ACTIONS = {
  // 로그인/로그아웃
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SYSTEM_ERROR: "LOGIN_SYSTEM_ERROR",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  // 비밀번호 관리
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGE_FAILED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_REQUEST_FAILED: "PASSWORD_RESET_REQUEST_FAILED",
  PASSWORD_RESET_SYSTEM_ERROR: "PASSWORD_RESET_SYSTEM_ERROR",
  PASSWORD_RESET_ERROR: "PASSWORD_RESET_ERROR",

  // 계정 관리
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED: "ACCOUNT_UNLOCKED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  LOGIN_ATTEMPTS_RESET: "LOGIN_ATTEMPTS_RESET",
  LOGIN_ATTEMPTS_RESET_ERROR: "LOGIN_ATTEMPTS_RESET_ERROR",

  // 보안 인증
  TURNSTILE_VERIFICATION_FAILED: "TURNSTILE_VERIFICATION_FAILED",
  AUTH_ERROR: "AUTH_ERROR",

  // 사용자 관리
  USER_CREATED: "USER_CREATED",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  WITHDRAW_SUCCESS: "WITHDRAW_SUCCESS",
  WITHDRAW_FAILED: "WITHDRAW_FAILED",
  WITHDRAW_ERROR: "WITHDRAW_ERROR",
  USER_SEARCH: "USER_SEARCH",
  USER_SEARCH_UNAUTHORIZED: "USER_SEARCH_UNAUTHORIZED",
  USER_SEARCH_FAILED: "USER_SEARCH_FAILED",
  USER_MISSING_EMAIL: "USER_MISSING_EMAIL",
  USER_PROFILE_ERROR: "USER_PROFILE_ERROR",

  // 프로필 관리
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",
  PROFILE_IMAGE_UPLOAD: "PROFILE_IMAGE_UPLOAD",
  PROFILE_IMAGE_UPLOAD_FAILED: "PROFILE_IMAGE_UPLOAD_FAILED",
  PROFILE_IMAGE_DELETE: "PROFILE_IMAGE_DELETE",
  PROFILE_IMAGE_DELETE_FAILED: "PROFILE_IMAGE_DELETE_FAILED",

  // IP 주소
  IP_ADDRESS_QUERY: "IP_ADDRESS_QUERY",
  IP_ADDRESS_QUERY_FAILED: "IP_ADDRESS_QUERY_FAILED",
} as const;

// ============================================
// 농장 관련 액션 (farm)
// ============================================
export const FARM_ACTIONS = {
  // 농장 CRUD
  FARM_CREATE: "FARM_CREATE",
  FARM_CREATE_FAILED: "FARM_CREATE_FAILED",
  FARM_READ: "FARM_READ",
  FARM_READ_FAILED: "FARM_READ_FAILED",
  FARM_UPDATE: "FARM_UPDATE",
  FARM_UPDATE_FAILED: "FARM_UPDATE_FAILED",
  FARM_DELETE: "FARM_DELETE",
  FARM_DELETE_FAILED: "FARM_DELETE_FAILED",

  // 농장 접근 제어
  FARM_MEMBER_ACCESS_DENIED: "FARM_MEMBER_ACCESS_DENIED",
  FARM_MEMBERS_FETCH_ERROR: "FARM_MEMBERS_FETCH_ERROR",
  FARM_MEMBER_ACCESS_CHECK_ERROR: "FARM_MEMBER_ACCESS_CHECK_ERROR",
  FARM_ACCESS_CHECK_ERROR: "FARM_ACCESS_CHECK_ERROR",
  FARM_LIST_FETCH_ERROR: "FARM_LIST_FETCH_ERROR",
} as const;

// ============================================
// 방문자 관련 액션 (visitor)
// ============================================
export const VISITOR_ACTIONS = {
  // 방문자 CRUD
  VISITOR_CREATED: "VISITOR_CREATED",
  VISITOR_CREATED_ERROR: "VISITOR_CREATED_ERROR",
  VISITOR_CREATION_FAILED: "VISITOR_CREATION_FAILED",
  VISITOR_UPDATED: "VISITOR_UPDATED",
  VISITOR_UPDATED_ERROR: "VISITOR_UPDATED_ERROR",
  VISITOR_UPDATE_FAILED: "VISITOR_UPDATE_FAILED",
  VISITOR_DELETED: "VISITOR_DELETED",
  VISITOR_DELETED_ERROR: "VISITOR_DELETED_ERROR",
  VISITOR_DELETE_FAILED: "VISITOR_DELETE_FAILED",

  // 방문자 등록
  VISITOR_REGISTRATION_SUCCESS: "VISITOR_REGISTRATION_SUCCESS",
  VISITOR_REGISTRATION_FAILED: "VISITOR_REGISTRATION_FAILED",
  VISITOR_REGISTRATION_EXCEPTION: "VISITOR_REGISTRATION_EXCEPTION",

  // 방문자 데이터 접근
  VISITOR_DATA_ACCESS: "VISITOR_DATA_ACCESS",
  VISITOR_FETCH_FAILED: "VISITOR_FETCH_FAILED",
  VISITOR_FETCH_ERROR: "VISITOR_FETCH_ERROR",

  // 방문자 세션 관리
  VISITOR_SESSION_NOT_FOUND: "VISITOR_SESSION_NOT_FOUND",
  VISITOR_SESSION_EXPIRED: "VISITOR_SESSION_EXPIRED",
  VISITOR_SESSION_VALID: "VISITOR_SESSION_VALID",
  VISITOR_SESSION_CHECK_ERROR: "VISITOR_SESSION_CHECK_ERROR",
  SESSION_CHECK_FAILED: "SESSION_CHECK_FAILED",

  // 방문자 제한
  VISITOR_DAILY_LIMIT_EXCEEDED: "VISITOR_DAILY_LIMIT_EXCEEDED",
  VISITOR_DAILY_LIMIT_WARNING: "VISITOR_DAILY_LIMIT_WARNING",
  VISITOR_ACCESS_DENIED: "VISITOR_ACCESS_DENIED",
  VISITOR_RECORD_NOT_FOUND: "VISITOR_RECORD_NOT_FOUND",
} as const;

// ============================================
// 멤버 관련 액션 (member)
// ============================================
export const MEMBER_ACTIONS = {
  // 멤버 CRUD
  MEMBER_READ: "MEMBER_READ",
  MEMBER_READ_FAILED: "MEMBER_READ_FAILED",
  MEMBER_CREATE: "MEMBER_CREATE",
  MEMBER_CREATE_FAILED: "MEMBER_CREATE_FAILED",
  MEMBER_UPDATE: "MEMBER_UPDATE",
  MEMBER_UPDATE_FAILED: "MEMBER_UPDATE_FAILED",
  MEMBER_DELETE: "MEMBER_DELETE",
  MEMBER_DELETE_FAILED: "MEMBER_DELETE_FAILED",
  MEMBER_BULK_READ: "MEMBER_BULK_READ",
  MEMBER_BULK_READ_FAILED: "MEMBER_BULK_READ_FAILED",
} as const;

// ============================================
// 알림 관련 액션 (notification)
// ============================================
export const NOTIFICATION_ACTIONS = {
  // VAPID 키 관리
  VAPID_KEY_CREATED: "VAPID_KEY_CREATED",
  VAPID_KEY_CREATE_FAILED: "VAPID_KEY_CREATE_FAILED",
  VAPID_KEY_RETRIEVED: "VAPID_KEY_RETRIEVED",
  VAPID_KEY_RETRIEVE_FAILED: "VAPID_KEY_RETRIEVE_FAILED",

  // 푸시 구독 관리
  PUSH_SUBSCRIPTION_FORCE_DELETE: "PUSH_SUBSCRIPTION_FORCE_DELETE",
  PUSH_SUBSCRIPTION_CREATED: "PUSH_SUBSCRIPTION_CREATED",
  PUSH_SUBSCRIPTION_GET: "PUSH_SUBSCRIPTION_GET",
  PUSH_SUBSCRIPTION_DELETED: "PUSH_SUBSCRIPTION_DELETED",
  PUSH_SUBSCRIPTION_CLEANUP: "PUSH_SUBSCRIPTION_CLEANUP",
  PUSH_SUBSCRIPTION_CLEANUP_NONE: "PUSH_SUBSCRIPTION_CLEANUP_NONE",
  PUSH_SUBSCRIPTION_CLEANUP_ALL_VALID: "PUSH_SUBSCRIPTION_CLEANUP_ALL_VALID",

  // 푸시 알림 전송
  PUSH_NOTIFICATION_SENT: "PUSH_NOTIFICATION_SENT",
  PUSH_NOTIFICATION_SEND_FAILED: "PUSH_NOTIFICATION_SEND_FAILED",
  PUSH_NOTIFICATION_NO_SUBSCRIBERS: "PUSH_NOTIFICATION_NO_SUBSCRIBERS",
  PUSH_NOTIFICATION_FILTERED_OUT: "PUSH_NOTIFICATION_FILTERED_OUT",
  PUSH_NOTIFICATION_INVALID_INPUT: "PUSH_NOTIFICATION_INVALID_INPUT",
  PUSH_NOTIFICATION_VAPID_INIT_FAILED: "PUSH_NOTIFICATION_VAPID_INIT_FAILED",
  PUSH_NOTIFICATION_SUBSCRIBER_FETCH_FAILED:
    "PUSH_NOTIFICATION_SUBSCRIBER_FETCH_FAILED",
  PUSH_NOTIFICATION_SETTINGS_FETCH_FAILED:
    "PUSH_NOTIFICATION_SETTINGS_FETCH_FAILED",

  // 알림 설정
  NOTIFICATION_SETTINGS_CREATION_FAILED:
    "NOTIFICATION_SETTINGS_CREATION_FAILED",
  NOTIFICATION_SETTINGS_READ_FAILED: "NOTIFICATION_SETTINGS_READ_FAILED",
  NOTIFICATION_SETTINGS_READ_SYSTEM_ERROR:
    "NOTIFICATION_SETTINGS_READ_SYSTEM_ERROR",
  NOTIFICATION_SETTINGS_UPDATE_FAILED: "NOTIFICATION_SETTINGS_UPDATE_FAILED",
  NOTIFICATION_SETTINGS_CREATE_FAILED: "NOTIFICATION_SETTINGS_CREATE_FAILED",
  NOTIFICATION_SETTINGS_UPDATE_SYSTEM_ERROR:
    "NOTIFICATION_SETTINGS_UPDATE_SYSTEM_ERROR",

  // 브로드캐스트
  BROADCAST_NOTIFICATION_SENT: "BROADCAST_NOTIFICATION_SENT",
  BROADCAST_NOTIFICATION_FAILED: "BROADCAST_NOTIFICATION_FAILED",
  BROADCAST_SENDING_FAILED: "BROADCAST_SENDING_FAILED",
} as const;

// ============================================
// 시스템 관련 액션 (system)
// ============================================
export const SYSTEM_ACTIONS = {
  // 스케줄링
  SCHEDULED_JOB: "SCHEDULED_JOB",
  BUSINESS_EVENT: "BUSINESS_EVENT",

  // 로그 관리
  LOG_DELETE: "LOG_DELETE",
  LOG_DELETE_FAILED: "LOG_DELETE_FAILED",

  // 데이터 관리
  EXPIRED_COUNT_INVALID_PARAMS: "EXPIRED_COUNT_INVALID_PARAMS",
  EXPIRED_COUNT_QUERY_FAILED: "EXPIRED_COUNT_QUERY_FAILED",

  // 파일 관리
  ORPHAN_FILE_CLEANUP: "ORPHAN_FILE_CLEANUP",
  ORPHAN_FILE_CLEANUP_ERROR: "ORPHAN_FILE_CLEANUP_ERROR",
  ORPHAN_FILES_CLEANUP_FAILED: "ORPHAN_FILES_CLEANUP_FAILED",

  // 시스템 설정
  INVALID_RETENTION_PERIOD: "INVALID_RETENTION_PERIOD",

  // 모니터링
  SYSTEM_RESOURCE_WARNING: "SYSTEM_RESOURCE_WARNING",
  MONITORING_HEALTH_CHECK_FAILED: "MONITORING_HEALTH_CHECK_FAILED",
  MONITORING_UPTIME_FAILED: "MONITORING_UPTIME_FAILED",
  MONITORING_ANALYTICS_FAILED: "MONITORING_ANALYTICS_FAILED",
  MONITORING_ERROR_LOGS_FAILED: "MONITORING_ERROR_LOGS_FAILED",

  // 시스템 오류
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // 설정 관련 액션 (통합)
  SETTINGS_INITIALIZE: "SETTINGS_INITIALIZE",
  SETTINGS_BULK_UPDATE: "SETTINGS_BULK_UPDATE",
  SETTINGS_UPDATE_ERROR: "SETTINGS_UPDATE_ERROR",

  // 보안 관련 액션 (통합)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  MALICIOUS_REQUEST_BLOCKED: "MALICIOUS_REQUEST_BLOCKED",
  SUSPICIOUS_LOGIN_ATTEMPTS: "SUSPICIOUS_LOGIN_ATTEMPTS",
} as const;

// ============================================
// 모든 액션 통합
// ============================================
export const ALL_LOG_ACTIONS = {
  ...AUTH_ACTIONS,
  ...FARM_ACTIONS,
  ...VISITOR_ACTIONS,
  ...MEMBER_ACTIONS,
  ...NOTIFICATION_ACTIONS,
  ...SYSTEM_ACTIONS,
} as const;

// 액션 타입
export type LogAction = (typeof ALL_LOG_ACTIONS)[keyof typeof ALL_LOG_ACTIONS];

// 카테고리별 액션 매핑
export const ACTIONS_BY_CATEGORY = {
  auth: Object.values(AUTH_ACTIONS),
  farm: Object.values(FARM_ACTIONS),
  visitor: Object.values(VISITOR_ACTIONS),
  member: Object.values(MEMBER_ACTIONS),
  notification: Object.values(NOTIFICATION_ACTIONS),
  system: Object.values(SYSTEM_ACTIONS),
} as const;
